# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - medicare

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_8fdf4fed6480472e9ccdd10bb622db7a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8bbf7ef7c62c41f9bb6aee41cb87a76e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8fdf4fed6480472e9ccdd10bb622db7a }}/dockerfile:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'medicare'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9339f7e4a7c24cf7898e353568cb5212 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8fdf4fed6480472e9ccdd10bb622db7a }}/dockerfile:${{ github.sha }}'
